name: Hourly
options:
  bundleIdPrefix: com.shimondeitel
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "Apple Distribution"
    PROVISIONING_PROFILE_SPECIFIER: "hourly appstore"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Hourly:
    type: application
    platform: iOS
    sources:
      - path: Hourly
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.hourly
        INFOPLIST_FILE: Hourly/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
schemes:
  Hourly:
    build:
      targets:
        Hourly: all
    run:
      config: Debug
    archive:
      config: Release
